
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 25 13:10:23 ICT 2016
//----------------------------------------------------

package com.trhoanglee.ast;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PLUSEQL = 43;
  public static final int DIVIDE = 29;
  public static final int MINUSEQL = 44;
  public static final int EQUALS = 33;
  public static final int PERIOD = 41;
  public static final int DIVEQL = 46;
  public static final int GREATER = 36;
  public static final int LPAREN = 21;
  public static final int INT = 2;
  public static final int LESS = 35;
  public static final int FOR = 11;
  public static final int MINUS = 27;
  public static final int RPAREN = 22;
  public static final int SIZEOF = 40;
  public static final int NOT = 30;
  public static final int SEMICOLON = 25;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int BOOL = 3;
  public static final int COMMA = 23;
  public static final int PLUS = 26;
  public static final int LESSEQ = 37;
  public static final int ASSIGN = 24;
  public static final int IF = 8;
  public static final int TIMESEQL = 45;
  public static final int ID = 13;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int DOUBLELITERAL = 16;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int PERCENT = 47;
  public static final int LCURLY = 17;
  public static final int NULL = 7;
  public static final int LSQBRACKET = 19;
  public static final int VOID = 4;
  public static final int RCURLY = 18;
  public static final int INTLITERAL = 14;
  public static final int TIMES = 28;
  public static final int ELSE = 9;
  public static final int NOTEQUALS = 34;
  public static final int WHILE = 10;
  public static final int ADDROF = 39;
  public static final int RSQBRACKET = 20;
  public static final int GREATEREQ = 38;
  public static final int STRINGLITERAL = 15;
  public static final int FALSE = 6;
  public static final int STRUCT = 42;
}

